#!/usr/bin/env bash
# Extracts the estimator functions EntropyLab implements from a checkout of the
# NIST SP 800-90B Entropy Assessment reference implementation, and wraps them in
# a standalone harness.
#
#   usage: scripts/reference-comparison/extract.sh <path-to-SP800-90B_EntropyAssessment>
#
# The full reference tool needs libdivsufsort, jsoncpp, bzip2 and OpenMP. Only
# the four estimator paths are needed for comparison, and they depend on far
# less, so they are lifted out rather than built in place. Everything below the
# header is copied line for line from the reference sources; nothing is retyped.
set -euo pipefail

REPO="${1:?path to SP800-90B_EntropyAssessment checkout required}"
CPP="$REPO/cpp"
OUT="$(dirname "$0")/nist_reference.cpp"
COMMIT="$(git -C "$REPO" rev-parse HEAD 2>/dev/null || echo unknown)"

UTILS="$CPP/shared/utils.h"
MCV="$CPP/shared/most_common.h"
COLLISION="$CPP/non_iid/collision_test.h"
LAG="$CPP/non_iid/lag_test.h"

# The reference functions end with verbose-printing blocks that reference
# globals this harness does not carry. Each extraction therefore stops at the
# line that computes the result and appends an explicit return, rather than
# trying to delete the printing statement by statement.
close_function() {
  printf '\treturn %s;\n}\n' "$1"
}

{
cat <<HEADER
// Reference estimator code extracted from the NIST SP 800-90B Entropy
// Assessment reference implementation.
//
//   source: https://github.com/usnistgov/SP800-90B_EntropyAssessment
//   commit: $COMMIT
//
// Generated by scripts/reference-comparison/extract.sh. Do not edit by hand.
//
// The estimator arithmetic below is copied from the reference sources rather
// than reimplemented, so a disagreement between this binary and EntropyLab is
// a disagreement with NIST's own code. Verbose printing and the JSON TestCase
// plumbing are removed; nothing else is changed.

#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cmath>
#include <cassert>
#include <cfloat>
#include <vector>
using namespace std;

#define INCLOSEDINTERVAL(x, a, b) (((a)>(b))?(((x)>=(b))&&((x)<=(a))):(((x)>=(a))&&((x)<=(b))))
#define INOPENINTERVAL(x, a, b) (((a)>(b))?(((x)>(b))&&((x)<(a))):(((x)>(a))&&((x)<(b))))
#define RELEPSILON DBL_EPSILON
#define ABSEPSILON DBL_MIN
#define DBL_INFINITY __builtin_inf ()
#define ITERMAX 1076
#define ZALPHA 2.5758293035489008

static inline double min(double a, double b) { return a < b ? a : b; }

HEADER

# relEpsilonEqual, used by the predictor binary search.
sed -n '80,163p' "$UTILS"
echo

# prediction_estimate_function and calc_p_local, used unchanged.
sed -n '842,953p' "$UTILS"
echo

# predictionEstimate, truncated at the entropy computation.
sed -n '955,975p' "$UTILS" \
  | sed 's/, const char \*testname, const int verbose, const char \*label//'
close_function entEst
echo

# most_common, truncated at the entropy computation.
sed -n '7,27p' "$MCV" \
  | sed 's/, const int verbose, const char \*label, TestCaseBase &tc//'
close_function entEst
echo

# F, col_exp and collision_test. The collision function interleaves verbose
# printing with its arithmetic, so it is taken as the contiguous ranges that
# carry the computation and the printing ranges are skipped.
sed -n '4,13p' "$COLLISION"
sed -n '15,40p' "$COLLISION" | sed 's/, const int verbose, const char \*label//'
sed -n '42,42p' "$COLLISION"
sed -n '52,56p' "$COLLISION"
sed -n '60,66p' "$COLLISION"
sed -n '68,68p' "$COLLISION"
sed -n '70,72p' "$COLLISION"
close_function entEst
echo

# lag_test, with its call into predictionEstimate adjusted for the trimmed
# signature.
sed -n '3,111p' "$LAG" \
  | sed -e 's/, const int verbose, const char \*label//' \
        -e 's/, "Lag", verbose, label)/)/'
echo

cat <<'HARNESS'

// Harness. Reads the alphabet size followed by whitespace-separated symbols on
// stdin and prints each estimator's result as JSON.
int main(void) {
    long alph = 0;
    if (scanf("%ld", &alph) != 1) return 1;

    vector<uint8_t> data;
    long value;
    while (scanf("%ld", &value) == 1) data.push_back((uint8_t)value);

    long len = (long)data.size();
    if (len < 3) return 1;

    printf("{\n");
    printf("  \"alphabetSize\": %ld,\n", alph);
    printf("  \"sampleCount\": %ld,\n", len);
    printf("  \"mostCommonValue\": %.17g,\n", most_common(data.data(), len, (int)alph));
    if (alph == 2) printf("  \"collision\": %.17g,\n", collision_test(data.data(), len));
    else printf("  \"collision\": null,\n");
    printf("  \"lagPredictor\": %.17g\n", lag_test(data.data(), len, (int)alph));
    printf("}\n");
    return 0;
}
HARNESS
} > "$OUT"

echo "wrote $OUT from $REPO @ $COMMIT"
