// Reference estimator code extracted from the NIST SP 800-90B Entropy
// Assessment reference implementation.
//
//   source: https://github.com/usnistgov/SP800-90B_EntropyAssessment
//   commit: 87c104d0ed4cbc96103e7b8b38d6f2c7e0a6b289
//
// Generated by scripts/reference-comparison/extract.sh. Do not edit by hand.
//
// The estimator arithmetic below is copied from the reference sources rather
// than reimplemented, so a disagreement between this binary and EntropyLab is
// a disagreement with NIST's own code. Verbose printing and the JSON TestCase
// plumbing are removed; nothing else is changed.

#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cmath>
#include <cassert>
#include <cfloat>
#include <vector>
using namespace std;

#define INCLOSEDINTERVAL(x, a, b) (((a)>(b))?(((x)>=(b))&&((x)<=(a))):(((x)>=(a))&&((x)<=(b))))
#define INOPENINTERVAL(x, a, b) (((a)>(b))?(((x)>(b))&&((x)<(a))):(((x)>(a))&&((x)<(b))))
#define RELEPSILON DBL_EPSILON
#define ABSEPSILON DBL_MIN
#define DBL_INFINITY __builtin_inf ()
#define ITERMAX 1076
#define ZALPHA 2.5758293035489008

static inline double min(double a, double b) { return a < b ? a : b; }

bool relEpsilonEqual(double A, double B, double maxAbsFactor, double maxRelFactor, uint32_t maxULP)
{
   double diff;
   double absA, absB;
   uint64_t Aint;
   uint64_t Bint;

   assert(sizeof(uint64_t) == sizeof(double));
   assert(maxAbsFactor >= 0.0);
   assert(maxRelFactor >= 0.0);

   ///NaN is by definition not equal to anything (including itself)
   if(std::isnan(A) || std::isnan(B)) {
      return false;
   }

   //Deals with equal infinities, and the corner case where they are actually copies
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wfloat-equal"
   if(A==B) {
      return true;
   }
#pragma GCC diagnostic pop

   //If either is infinity, but they are not equal, then they aren't close.
   if(std::isinf(A) || std::isinf(B)) {
      return false;
   }

   absA = fabs(A);
   absB = fabs(B);
   //Make sure that A is the closest to 0.
   if(absA > absB) {
      double tmp;

      //Swap A and B
      tmp = B;
      B=A;
      A=tmp;

      //Swap absA and absB
      tmp = absB;
      absB = absA;
      absA = tmp;
   }

   //Capture the difference of the largest magnitude from the smallest magnitude
   diff=fabs(B-A);

   //Is absA, diff, or absB * maxRelFactor subnormal?
   //Did diff overflow?
   //if absA is subnormal (effectively 0) or 0, then relative difference isn't meaningful, as fabs(B-A)/B≈1 for all values of B
   //In the instance of overflows, the resulting relative comparison will be nonsense.
   if((absA < DBL_MIN) || (diff < DBL_MIN) || std::isinf(diff) || (absB * maxRelFactor < DBL_MIN)) {
      //Yes. Relative closeness is going to be nonsense
      return diff <= maxAbsFactor;
   } else {
      //No. Using relative closeness is probably the right thing to do.
      //Proceeding roughly as per Knuth AoCP vol II (section 4.2.2)
      if(diff <= absB * maxRelFactor) {
         //These are relatively close
         return true;
      } 
   }

   //Neither A or B is subnormal, and they aren't close in the conventional sense, 
   //but perhaps that's just due to IEEE representation. Check to see if the value is within maxULP ULPs.

   //We can't meaningfully compare non-zero values with 0.0 in this way,
   //but absA >= DBL_MIN if we're here, so neither value is 0.0.

   //if they aren't the same sign, then these can't be only a few ULPs away from each other
   if(signbit(A) != signbit(B)) {
      return false;
   }

   //Note, casting from one type to another is undefined behavior, but memcpy will necessarily work
   memcpy(&Aint, &absA, sizeof(double));
   memcpy(&Bint, &absB, sizeof(double));
   //This should be true by the construction of IEEE doubles
   assert(Bint > Aint);

   return (Bint - Aint <= maxULP);
}

double prediction_estimate_function(long double p, long r, long N){
	long double q, x, xlast=0.0L;
	assert(p > 0.0L); //In fact, it is >= 1/k
	assert(p < 1.0L);

	q = 1.0L-p;
	x = 1.0L;

	//We know that 
	// * x is in the interval [1,1/p] which is a subset of [1,k]
	// * the sequence is monotonic up (so x >= xlast).
	//As such we don't need much fancyness for looking for "equality"
	for(int i = 0; (i <= 65) && ((x - xlast) > (LDBL_EPSILON*x)); i++) {
		xlast = x;
		x = 1.0L + q*powl(p, r)*powl(x, r+1.0L);
		//We expect this convergence to be monotonic up.
		assert(x >= xlast);
		//We expect x<=1/p
		assert(p*x <= 1.0L);
	}

	return((double)(logl(1.0L-p*x) - logl((r+1.0L-r*x)*q) - (N+1.0L)*logl(x)));
}

double calc_p_local(long max_run_len, long N, double ldomain){
	int j;
	double p, log_alpha;
	double lastP, pVal;
	double lvalue, hvalue;
	double hbound, lbound;
	double hdomain;

	// binary search for p_local
	log_alpha = log(0.99);
	
	hdomain = 1.0;

	lbound = ldomain;
	hbound = hdomain;

	lvalue = DBL_INFINITY;
	hvalue = -DBL_INFINITY;

	//Note that the bounds are in [0,1], so overflows aren't an issue
	//But underflows are.
	p = (lbound + hbound) / 2.0;
	pVal = prediction_estimate_function(p, max_run_len+1, N);

	//We don't need the initial pVal invariant, as our initial bounds are infinite.
	//We don't need the initial bounds, as they are set to the domain bounds
	for(j=0; j<ITERMAX; j++) {
		//Have we reached "equality"?
		if(relEpsilonEqual(pVal, log_alpha, ABSEPSILON, RELEPSILON, 4)) break;

		//Now update based on the found pVal
		if(log_alpha < pVal) {
			lbound = p;
			lvalue = pVal;
		} else {
			hbound = p;
			hvalue = pVal;
		}

		//We now verify that ldomain <= lbound < p < hbound <= hdomain
		//and that target in [ lvalue, hvalue ]
		if(lbound >= hbound) {
			p = fmin(fmax(lbound, hbound),hdomain);
			break;
		}

		//invariant. If this isn't true, then we can't evaluate here.
		if(!(INCLOSEDINTERVAL(lbound, ldomain, hdomain) && INCLOSEDINTERVAL(hbound,  ldomain, hdomain))) {
			p = hdomain;
			break;
		}

		//invariant. If this isn't true, then seeking the value within this interval doesn't make sense.
		if(!INCLOSEDINTERVAL(log_alpha, lvalue, hvalue)) {
			p = hdomain;
			break;
		}

		//Update p
		lastP = p;
		p = (lbound + hbound) / 2.0;

		//invariant. If this isn't true, then further calculation isn't really meaningful.
		if(!INOPENINTERVAL(p,  lbound, hbound)) {
			p = hbound;
			break;
		}

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wfloat-equal"
		//Look for a cycle
		if(lastP == p) {
			p = hbound;
			break;
		}
#pragma GCC diagnostic pop

		pVal = prediction_estimate_function(p, max_run_len+1, N);

		//invariant: If this isn't true, then this isn't loosely monotonic
		if(!INCLOSEDINTERVAL(pVal, lvalue, hvalue)) {
			p = hbound;
			break;
		}
	}//for loop

	return p;
}

double predictionEstimate(long C, long N, long max_run_len, long k) {
	double curMax;
	double p_local=-1.0;
	double entEst;
	double p_global;
	double p_globalPrime;

	curMax = 1.0 / ((double)k);

	p_global = (double)C/(double)N;

	if(p_global > 0) p_globalPrime = min(1.0, p_global + ZALPHA*sqrt((p_global*(1.0-p_global))/((double)N-1.0)));
	else p_globalPrime = 1.0 - pow(0.01, 1.0/(double)N);

	curMax = fmax(curMax, p_globalPrime);
	if((curMax < 1.0) && (prediction_estimate_function(curMax, max_run_len+1, N) > log(0.99))) {
		p_local = calc_p_local(max_run_len, N, curMax);
		curMax = fmax(curMax, p_local);
	}

	entEst = -log2(curMax);
	return entEst;
}

double most_common(uint8_t* data, const long len, const int alph_size){

	long counts[alph_size];
	long i, mode;
	double pmax, ubound;
	double entEst;

	assert(len > 1);

	for(i = 0; i < alph_size; i++) counts[i] = 0;
	for (i = 0; i < len; i++) counts[data[i]]++;

	mode = 0;
	for(i = 0; i < alph_size; i++){
		if(counts[i] > mode) mode = counts[i];
	}

	pmax = mode/(double)len;

	ubound = min(1.0,pmax + ZALPHA*sqrt(pmax*(1.0-pmax)/(len-1.0)));
	entEst = -log2(ubound);
	return entEst;
}

// Computed using efficient implementation in Appendix G.1.1
double F(double q){
   return q*(2.0*q*q+2.0*q+1.0);
}

double col_exp(double p){
	double q = 1.0 - p;

	return (p/(q*q))*(1.0 + 0.5*(1.0/p - 1.0/q))*F(q) - (p/q)*0.5*(1.0/p - 1.0/q);
}
// Section 6.3.2 - Collision Estimate
// data is assumed to be binary (e.g., bit string)
double collision_test(uint8_t* data, long len){
	long v, i;
	int t_v;
	double X, s, p;
	double entEst;

	i = 0;
	v = 0;
	s = 0.0;

	// compute wait times until collisions
	while(i < len-1){
		if(data[i] == data[i+1]) t_v = 2; // 00 or 11
		else if(i < len-2) t_v = 3; // 101, 011, 100, or 101
		else break;
		
		v++;
		s += t_v*t_v;
		i += t_v;
	}

	// X is mean of t_v's, s is sample stdev, where
	// s^2 = (sum(t_v^2) - sum(t_v)^2/v) / (v-1)
	X = i / (double)v;
	s = sqrt((s - (i*X)) / (v-1));
	// Directly calculate p
	X -= ZALPHA * s/sqrt(v);
	//2 is the smallest meaninful value here.
	if(X < 2.0) X = 2.0;

	//Uyen Dinh observed that (with the simpler F function described in UL comments) we can simplify the entire expression much further than in 90B.
	//The whole mess in 90B step 7 reduces to X'-bar = -2p^2 + 2p + 2, which we can solve using the quadratic formula.
	//We only care about the root greater than 0.5, so we only care about the "+" branch.
	//If the meanbound > 2.5, then the roots become complex, so this isn't well defined (and is processed as per the error handling specified in 90B).
	if(X < 2.5) {
		p = 0.5 + sqrt(1.25 - 0.5 * X);
		entEst = -log2(p);
	} else {
		p = 0.5;
		entEst = 1.0;
	}
	return entEst;
}


#define D_LAG 128U
#define LAGMASK (D_LAG-1)

/*Convention:
 * if start==end, the buffer is empty. Start and end values are not ANDed, so range from 0...255
 * This extended range allows for use of all the entries of the buffer
 * See https://www.snellman.net/blog/archive/2016-12-13-ring-buffers/
 * The actual data locations range 0...127
 * start&LAGMASK is the index of the oldest data
 * end&LAGMASK is the index where the *next* data goes.
 */

struct lagBuf {
	uint8_t start;
	uint8_t end;
	long buf[D_LAG];
};

/* Lag prediction estimate (6.3.8)
 * This is a somewhat counter-intuitive approach to this test; the original idea for this approach is due
 * to David Oksner. The straight forward way is simply to check j symbols back for each case (where j runs
 * 1 to 128). It ends up that this is bizarrely slow.
 * This approach is to keep a list of offsets where we encountered each symbol (in a ring buffer,
 * which can store at most D (128) prior elements.
 * For this, one needs only check and update the current symbol's ring buffer, and we only need to spend
 * time looking at values that correspond to counters that must be updated.
 */
double lag_test(uint8_t *S, long L, int k) {
	long scoreboard[D_LAG] = {0};
	int winner = 0;
	long curRunOfCorrects = 0;
	long maxRunOfCorrects = 0;
	long correctCount = 0;
	lagBuf *ringBuffers;
	long highScore = 0;

	assert(S != NULL);
	assert(L > 2);
	assert(k >= 2);

	ringBuffers = new lagBuf[k];

	//Flag all the rings as empty
	for (int j = 0; j < k; j++) {
		ringBuffers[j].start = 0;
		ringBuffers[j].end = 0;
	}

	// Account for the very first symbol (there isn't a guess for this one)
	ringBuffers[S[0]].buf[0] = 0;
	ringBuffers[S[0]].start = 0;
	ringBuffers[S[0]].end = 1;

	// The rest of the values yield a prediction
	for (long i = 1; i < L; i++) {
		const uint8_t curSymbol = S[i];
		lagBuf *const curRingBuffer = &(ringBuffers[curSymbol]); // The pointer itself is a constant (not the structure it points to)

		// Check the prediction first
		if (curSymbol == S[i - winner - 1]) {
			correctCount++;
			curRunOfCorrects++;
			if (curRunOfCorrects > maxRunOfCorrects) {
				maxRunOfCorrects = curRunOfCorrects;
			}
		} else {
			curRunOfCorrects = 0;
		}

		// Update counters
		if (curRingBuffer->start != curRingBuffer->end) {
			uint8_t counterIndex = curRingBuffer->end;
			const long cutoff = (i >= D_LAG) ? (i - D_LAG) : 0;  // Cutoff is the oldest stream index that should be present in the buffer

			do {
				counterIndex--;
				if (curRingBuffer->buf[counterIndex&LAGMASK] >= cutoff) {
					long curScore;
					long curOffset;
					curOffset = i - curRingBuffer->buf[counterIndex&LAGMASK] - 1;
					assert(curOffset < D_LAG);
					curScore = ++scoreboard[curOffset];

					if (curScore >= highScore) {
						winner = curOffset;
						highScore = curScore;
					}
				} else {
					// The correct start was the prior symbol (which is the next symbol in the buffer)
					curRingBuffer->start = (uint8_t)(counterIndex + 1U);
					break;
				}
			} while (counterIndex != curRingBuffer->start);
		}

		// Add the new symbol
		// Are we already full? If so, advance the start index.
		if((uint8_t)(curRingBuffer->end - curRingBuffer->start) == D_LAG) curRingBuffer->start++;
		//Add the current offset and adjust the end index
		curRingBuffer->buf[(curRingBuffer->end)&LAGMASK] = i;
		curRingBuffer->end++;
		assert((uint8_t)(curRingBuffer->end - curRingBuffer->start) <= D_LAG);
	}

	delete[] ringBuffers;

	return predictionEstimate(correctCount, L-1, maxRunOfCorrects, k);
}


// Harness. Reads the alphabet size followed by whitespace-separated symbols on
// stdin and prints each estimator's result as JSON.
int main(void) {
    long alph = 0;
    if (scanf("%ld", &alph) != 1) return 1;

    vector<uint8_t> data;
    long value;
    while (scanf("%ld", &value) == 1) data.push_back((uint8_t)value);

    long len = (long)data.size();
    if (len < 3) return 1;

    printf("{\n");
    printf("  \"alphabetSize\": %ld,\n", alph);
    printf("  \"sampleCount\": %ld,\n", len);
    printf("  \"mostCommonValue\": %.17g,\n", most_common(data.data(), len, (int)alph));
    if (alph == 2) printf("  \"collision\": %.17g,\n", collision_test(data.data(), len));
    else printf("  \"collision\": null,\n");
    printf("  \"lagPredictor\": %.17g\n", lag_test(data.data(), len, (int)alph));
    printf("}\n");
    return 0;
}
