/**
 * Runs every estimator against every adversarial fixture and writes the
 * results to docs/proof-campaign/.
 *
 * Nothing in the published campaign is typed by hand. Every number in every
 * generated file comes from this run, so a reader can regenerate the directory
 * and diff it against what is committed.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { analyze, type EstimatorResult } from "@entropylab/core";
import { allFixtures } from "@entropylab/fixtures";
import { buildReport, renderMarkdown, type ProcessProfile } from "@entropylab/report";

const outputDir = join(dirname(fileURLToPath(import.meta.url)), "..", "docs", "proof-campaign");

const ESTIMATOR_ORDER = ["most-common-value", "collision", "markov", "lag-predictor"] as const;

function bitsFor(results: EstimatorResult[], id: string): number | null {
  const result = results.find((entry) => entry.id === id);
  if (!result?.applicable || result.bitsPerSymbol === undefined) return null;
  return result.bitsPerSymbol;
}

function cell(value: number | null): string {
  return value === null ? "declined" : value.toFixed(4);
}

function main(): void {
  mkdirSync(outputDir, { recursive: true });

  const fixtures = allFixtures();
  const rows: string[] = [];
  const summary: Record<string, unknown>[] = [];

  for (const fixture of fixtures) {
    const analysis = analyze(fixture.sample);
    const profile: ProcessProfile = {
      name: fixture.label,
      sourceType: fixture.sample.alphabetSize === 6 ? "d6" : "custom",
      alphabetSize: fixture.sample.alphabetSize,
      collectionMethod: `synthetic fixture ${fixture.id}`,
      notes: fixture.defect,
    };
    const report = buildReport({
      profile,
      sample: fixture.sample,
      analysis,
      datasetSource: fixture.id,
    });

    writeFileSync(
      join(outputDir, `${fixture.id}.json`),
      `${JSON.stringify(report, null, 2)}\n`,
      "utf8",
    );
    writeFileSync(join(outputDir, `${fixture.id}.md`), renderMarkdown(report), "utf8");

    const values = ESTIMATOR_ORDER.map((id) => bitsFor(analysis.estimators, id));
    rows.push(
      `| ${fixture.id} | ${values.map(cell).join(" | ")} | ` +
        `${analysis.conservativeBitsPerSymbol?.toFixed(4) ?? "none"} | ` +
        `${analysis.limitingEstimator ?? "none"} |`,
    );

    summary.push({
      fixture: fixture.id,
      defect: fixture.defect,
      sampleCount: analysis.sampleCount,
      idealBitsPerSymbol: analysis.idealBitsPerSymbol,
      estimators: Object.fromEntries(ESTIMATOR_ORDER.map((id, i) => [id, values[i]])),
      conservativeBitsPerSymbol: analysis.conservativeBitsPerSymbol ?? null,
      limitingEstimator: analysis.limitingEstimator ?? null,
      inputHash: report.dataset.inputHash,
    });
  }

  writeFileSync(
    join(outputDir, "results.json"),
    `${JSON.stringify({ algorithmVersion: fixtures.length > 0 ? analyze(fixtures[0]!.sample).version : null, results: summary }, null, 2)}\n`,
    "utf8",
  );

  const doc = [
    "# Proof campaign",
    "",
    "Generated by `pnpm campaign`. Every number below is written by that script.",
    "Regenerate the directory and diff it to check any figure quoted elsewhere.",
    "",
    "All figures are estimated min-entropy in bits per symbol. The ideal for a",
    "six-symbol alphabet is 2.5850.",
    "",
    "| Fixture | Most common value | Collision | Markov | Lag predictor | Conservative | Limiting |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "## What this table shows",
    "",
    "Read the PERIODIC_BALANCED row across. The most common value estimate rates",
    "it above every other fixture, including the genuinely random control, because",
    "its histogram is exactly uniform while a real random draw carries sampling",
    "noise. The sequence is `0,1,2,3,4,5` repeating: the next symbol is certain.",
    "The sequential estimators report it at effectively zero.",
    "",
    "That single row is the argument for the whole tool. A process can be perfect",
    "under the check most people apply and worthless in fact.",
    "",
    "STICKY_MARKOV makes the same point in a form closer to a real defect. Its",
    "histogram is within sampling noise of the fair control, so frequency analysis",
    "sees almost nothing, while the lag predictor identifies lag 1 as the winning",
    "lag: the die is repeating its previous face.",
    "",
    "BIASED is the control for the opposite direction. The defect is in the",
    "histogram alone, the frequency estimator is limiting, and the lag predictor",
    "understates it. Neither family dominates, which is why the pipeline reports",
    "the minimum across all of them.",
    "",
    "LOW_SAMPLE uses the same generator as FAIR_LIKE with 40 observations instead",
    "of 6000. The sequential estimators decline rather than return a number. The",
    "correct response to too little data is to say so.",
    "",
    "## Per-fixture reports",
    "",
    ...fixtures.map(
      (f) => `- **${f.id}** ([JSON](./${f.id}.json), [Markdown](./${f.id}.md)) ${f.defect}`,
    ),
    "",
  ].join("\n");

  writeFileSync(join(outputDir, "README.md"), doc, "utf8");

  process.stdout.write(`Wrote campaign results for ${fixtures.length} fixtures to ${outputDir}\n`);
  for (const row of rows) process.stdout.write(`${row}\n`);
}

main();
